parameters:
  cronjob.service: MH1\CronBundle\Service\DoctrineCronJobService
  cronjob.log.service: MH1\CronBundle\Service\DoctrineCronJobLogService
  cronjob.check_interval: 1000000
  cronjob.execution_time_zone: null
